---
title: "Assignment_1"
author: "Andriy Sinclair"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Predicting business reviews with machine learning

## TDSP Methodology

## 1. Business Understanding

**Why do we want to predict business reviews?**

This information would be useful for current and prospective business owners, who want to obtain the best possible business image in the eyes of their customers. A survey conducted in 2014, found that reviews were the second most important factor after price when considering a purchase. In fact, 95% of customers use reviews, 86% say they are essential when making a purchase and nearly one-third of those aged under 45 consult them for every single purchase . Clearly, positive reviews are crucial to businesses[^1]. Hence, our model needs interpretability since business owners seek to understand the key factors influencing positive reviews, allowing them to adjust their behaviour accordingly. Good out-of-sample predictability is also necessary, especially to prospective business owners who may use these results when considering their business plan.

## 2. Data Acquisitions and Understanding

Three data sets, which can be found here[^2], have been used in this project:

* User data set
  * contains yelp user specific information such as: the number of reviews they have written and the average rating of a review
* Review data set
  * contains review specific information such as: the star rating (this is the variable we will try to redict)
* Business data set
  * contains business specific information such as: the name, the state and the rating of the business
  
Each data set was cleaned individually before merging into one data set.

**User data set**

* "user_id" column, which provided a unique identifier for each user was checked for duplicate values
* The data set was checked for missing values
* The columns where checked for empty values: "elite"  had over 95% empty values was dropped
* "yelping since", what do we want to do with this?
* "friends" contained a list of the user's friends by identification number, this was converted to include the number of friends a user had so that the data was numeric and could be worked with
* 


## Models

**Overview**

Include all models w&w/o SA for MSE

Include classification models graph

While reviews are discrete outcome variables ranging from 0 to 5, treating this prediction as a classification problem might not capture the nuanced relationships between values. For instance, predicting 4 when the actual value is 5 and predicting 1 when the actual value is 5 both result in the same classification score of 0. Treating it as a regression problem with Mean Squared Error (MSE) as a performance measure allows the model to receive credit for distinguishing a good reviews from bad, even if the exact value was not predicted correctly.
MSE is defined as:

$$MSE = \frac{1}{n} \sum_{i=1}^{n} (y_i - \hat{y}_i)^2$$

MSE takes into account the average squared deviation of the value predicted by the model from the actual value. 

**OLS**

OLS (Ordinary Least Squares) was a primarily chosen as a widely-used and well-known prediction method, that could be used as a benchmark. Additionally, Its interpretability surpasses that of more intricate models. If the Classical Linear Regression Model (CLRM) assumptions hold, OLS not only provides insights into the relative contribution of predictors to the outcome variable but also offers a clear understanding of the expected magnitude of their influence.

A multivariate regression specification, like the one used in this project, can be defined as follows:

$$Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \ldots + \beta_k X_k + \varepsilon$$

We choose the \( \beta_0, \beta_1,..., \beta_k\) that minimises the RSS (residual sum of squares), defined as:

\begin{align*}
RSS &= \sum_{i=1}^{n}(y_i - \hat{y}_i)^2 \\
    &= \sum_{i=1}^{n}(y_i - \hat{\beta}_0 - \hat{\beta}_1x_{i1} - \hat{\beta}_2x_{i2} - \ldots - \hat{\beta}_kx_{ik})^2
\end{align*}

Our




Give an explanation here of the different variables

A 




**Shrinkage methods**

*Lasso*

*Ridge*



## Evaluation

Why do some models work better for this task compared to others

Weighted sentiment score vs Normal Sentiment score

How could we have improved
  

The review data set contained: "review_id", "user_id" and "business_id", which could be merged with "business_id" on the business dataset and "user_id" on the user data set. 





## Bibliography

[^1]: https://www.powerreviews.com/blog/survey-confirms-the-value-of-reviews/
[^2]: https://www.yelp.com/dataset


## Appendix

### Appendix 1: Datasets used ###

**Business data set**

- **business_id**: A string representing a 22-character unique business ID.
- **name**: A string representing the business's name.
- **address**: A string representing the full address of the business.
- **city**: A string representing the city where the business is located.
- **state**: A string representing the 2-character state code, if applicable.
- **postal_code**: A string representing the postal code of the business.
- **latitude**: A float representing the latitude of the business location.
- **longitude**: A float representing the longitude of the business location.
- **stars**: A float representing the star rating of the business, rounded to half-stars.
- **review_count**: An integer indicating the number of reviews for the business.
- **is_open**: An integer, 0 or 1, indicating whether the business is closed or open, respectively.
- **attributes**: An object representing business attributes, where some attribute values might be objects.
  - **RestaurantsTakeOut**: A boolean indicating whether the business offers takeout.
  - **BusinessParking**: An object with boolean values indicating parking options (e.g., garage, street, valet).
- **categories**: An array of strings representing business categories.
- **hours**: An object representing the hours of operation for each day of the week, using a 24hr clock.

**User data set**

- **user_id**: A string representing a unique 22-character user ID, mapping to the user in user.json.
- **name**: A string representing the user's first name.
- **review_count**: An integer indicating the number of reviews the user has written.
- **yelping_since**: A string indicating when the user joined Yelp, formatted as YYYY-MM-DD.
- **friends**: An array of strings representing user IDs of the user's friends.
- **useful**: An integer indicating the number of useful votes sent by the user.
- **funny**: An integer indicating the number of funny votes sent by the user.
- **cool**: An integer indicating the number of cool votes sent by the user.
- **fans**: An integer indicating the number of fans the user has.
- **elite**: An array of integers representing the years the user was elite.
- **average_stars**: A float indicating the average rating of all reviews given by the user.
- **compliment_hot**: An integer indicating the number of hot compliments received by the user.
- **compliment_more**: An integer indicating the number of more compliments received by the user.
- **compliment_profile**: An integer indicating the number of profile compliments received by the user.
- **compliment_cute**: An integer indicating the number of cute compliments received by the user.
- **compliment_list**: An integer indicating the number of list compliments received by the user.
- **compliment_note**: An integer indicating the number of note compliments received by the user.
- **compliment_plain**: An integer indicating the number of plain compliments received by the user.
- **compliment_cool**: An integer indicating the number of cool compliments received by the user.
- **compliment_funny**: An integer indicating the number of funny compliments received by the user.
- **compliment_writer**: An integer indicating the number of writer compliments received by the user.
- **compliment_photos**: An integer indicating the number of photo compliments received by the user.

**Review dataset**

- **review_id**: A string representing a unique 22-character review ID.
- **user_id**: A string representing a unique 22-character user ID, mapping to the user in user.json.
- **business_id**: A string representing a unique 22-character business ID, mapping to business in business.json.
- **stars**: An integer indicating the star rating of the review.
- **date**: A string representing the date of the review formatted as YYYY-MM-DD.
- **text**: A string representing the text content of the review.
- **useful**: An integer indicating the number of useful votes received for the review.
- **funny**: An integer indicating the number of funny votes received for the review.
- **cool**: An integer indicating the number of cool votes received for the review.






